import type { Metadata } from "next";
import { Inter , Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import Header from "./Header";
import { Toaster } from "@afs/components/ui/toaster";

import { Bell, ChevronLeft, ChevronRight, Home, LayoutDashboard, Menu, Settings, User, X } from "lucide-react"
import Link from "next/link" 
import { useState } from "react";
import { SidebarProvider, SidebarTrigger } from "@afs/components/ui/sidebar"
import { AppSidebar } from "@afs/components/custom/app-sidebar"

 

const poppins = Poppins({
  subsets: ['latin'],
  weight : '400',
})
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" >
      <body className={inter.className}>
        <Providers>
      {/* <SidebarProvider
      > */}
      {/* <AppSidebar /> */}
      <main>
      {/* <SidebarTrigger /> */}
        {/* <Header /> */}
        {children}
        <Toaster />
      </main>
      {/* </SidebarProvider> */}
        </Providers>
        </body>
    </html>
  );
}
