import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import Header from "./Header";
import { Toaster } from "@afs/components/ui/toaster";

import { Bell, ChevronLeft, ChevronRight, Home, LayoutDashboard, Menu, Settings, User, X } from "lucide-react"
import Link from "next/link" 
import { useState } from "react";
import { SidebarProvider, SidebarTrigger } from "@afs/components/ui/sidebar"
import { AppSidebar } from "@afs/components/custom/app-sidebar"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [sidebarExpanded, setSidebarExpanded] = useState(true)
  // const [isMobile, setIsMobile] = useState(false)


  // const SidebarContent = () => (
  //   <nav className="p-4">
  //     <ul className="space-y-2">
  //       {[
  //         { icon: Home, label: "Home", href: "#" },
  //         { icon: LayoutDashboard, label: "Dashboard", href: "#", active: true },
  //         { icon: User, label: "Profile", href: "#" },
  //         { icon: Settings, label: "Settings", href: "#" },
  //       ].map((item, index) => (
  //         <li key={index}>
  //           <Link
  //             href={item.href}
  //             className={`flex items-center rounded-lg p-2 ${
  //               item.active
  //                 ? "bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-white"
  //                 : "text-gray-600 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-700"
  //             } ${!sidebarExpanded && !isMobile ? "justify-center" : ""}`}
  //           >
  //             <item.icon className="h-5 w-5" />
  //             {(sidebarExpanded || isMobile) && <span className="ml-3">{item.label}</span>}
  //           </Link>
  //         </li>
  //       ))}
  //     </ul>
  //   </nav>
  // )




  return (
    <html lang="en" >
      <body className={inter.className}>
        <Providers>
      <SidebarProvider>
      <AppSidebar />
      <main>
      <SidebarTrigger />
        <Header />
        {children}
        <Toaster />
      </main>
      </SidebarProvider>
        </Providers>
        </body>
    </html>
  );
}
